listA = [1, 4, 3, 0]
listB = ['x', 'z', 't', 'q']
print('listA is: ', listA)
print(listA.sort)
print('listA.sort is: ', listA.sort)
print(listA.sort())
print('listA.sort() is: ', listA.sort())

print(listA)
print(listA.insert(0, 100))
print("listA.remove(3): ")

print(listA.remove(3))
print(listA.append(7))
print('listA is: ', listA)
print('listA + listB is: ', listA + listB)
print('listB.sort() is: ', listB.sort())
print('listB is:', listB)
print('listB.pop() is:', listB.pop())
print('listB.count ("a") is: ', listB.count('a'))
#print('lisB.remove("a") is: ', listB.remove('a'))
print('listA.extend is: ', listA.extend([4, 1, 6, 3, 4]))
print('listA.count(4) is:', listA.count(4))
print('listA is: ', listA)
print('listA.index(1) is:', listA.index(1))
print('listA.pop(4) is:', listA.pop(4))
print('listA is: ', listA)
print('listA.reverse()',listA.reverse())
print(listA)